<?php
$exercises = [
                    "Saying Hello",
                    "Counting the Number of Characters",
                    "Printing Quotes",
                    "Mad Lib",
                    "Simple Math",
                    "Retirement Calculator",
                    "Area of a Rectangular Room",
                    "Pizza Party",
                    "Paint Calculator",
                    "Self-Checkout",
                    "Currency Conversion",
                    "Computing Simple Interest",
                    "Determining Compound Interest",
                    "Tax Calculator",
                    "Password Validation",
                    "Legal Driving Age",
                    "Blood Alcohol Calculator",
                    "Temperature Converter",
                    "BMI Calculator",
                    "Multistate Sales Tax Calculator",
                    "Numbers to Names",
                    "Comparing Numbers",
                    "Troubleshooting Car Issues",
                    
             ];